name: PR Checks
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: ls
        run: ls
#      - name: Set up python
#        id: setup-python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.10.4
#      - name: Install Just
#        uses: extractions/setup-just@v1
#      - name: Install Poetry
#        uses: abatilo/actions-poetry@v2.0.0
#        with:
#          poetry-version: 1.1.13
#      - name: Install Flyway
#        run: sudo snap install flyway
#      - name: Install Dependencies
#        run: poetry install
#      - name: Run Tests
#        run: just test